package com.stripe.android;

import android.os.Parcel;
import android.os.Parcelable;
import androidx.activity.result.AbstractC0343d;
import com.stripe.android.core.exception.StripeException;
import com.stripe.android.model.PaymentIntent;
import com.stripe.android.model.SetupIntent;
import com.stripe.android.model.Source;
import com.stripe.android.model.Stripe3ds2AuthParams;
import com.stripe.android.model.StripeIntent;
import com.stripe.android.payments.PaymentFlowResult;
import com.stripe.android.view.AuthActivityStarter;
import com.stripe.android.view.AuthActivityStarterHost;
import com.stripe.android.view.PaymentRelayActivity;
import java.io.Serializable;
import p001a.C0048o;
import p002a0.C0118m0;
import p072df.C3330f;
import p072df.C3335k;
import p353te.C9453f;
import tf.C9508y;
/* compiled from: PaymentRelayStarter.kt */
/* loaded from: classes.dex */
public interface PaymentRelayStarter extends AuthActivityStarter<Args> {

    /* compiled from: PaymentRelayStarter.kt */
    /* loaded from: classes.dex */
    public static abstract class Args implements Parcelable {
        public static final int $stable = 0;
        public static final Companion Companion = new Companion(null);

        /* compiled from: PaymentRelayStarter.kt */
        /* loaded from: classes.dex */
        public static final class Companion {
            private Companion() {
            }

            public /* synthetic */ Companion(C3330f c3330f) {
                this();
            }

            public static /* synthetic */ Args create$default(Companion companion, StripeIntent stripeIntent, String str, int i, Object obj) {
                if ((i & 2) != 0) {
                    str = null;
                }
                return companion.create(stripeIntent, str);
            }

            public final Args create(StripeIntent stripeIntent, String str) {
                C3335k.m11451e(stripeIntent, "stripeIntent");
                if (stripeIntent instanceof PaymentIntent) {
                    return new PaymentIntentArgs((PaymentIntent) stripeIntent, str);
                }
                if (stripeIntent instanceof SetupIntent) {
                    return new SetupIntentArgs((SetupIntent) stripeIntent, str);
                }
                throw new C9508y();
            }
        }

        /* compiled from: PaymentRelayStarter.kt */
        /* loaded from: classes.dex */
        public static final class ErrorArgs extends Args {
            private final StripeException exception;
            private final int requestCode;
            public static final Companion Companion = new Companion(null);
            public static final Parcelable.Creator<ErrorArgs> CREATOR = new Creator();
            public static final int $stable = 8;

            /* compiled from: PaymentRelayStarter.kt */
            /* loaded from: classes.dex */
            public static final class Companion {
                private Companion() {
                }

                public /* synthetic */ Companion(C3330f c3330f) {
                    this();
                }

                /* renamed from: newArray */
                public ErrorArgs[] m15011newArray(int i) {
                    throw new C9453f("Generated by Android Extensions automatically");
                }

                /* renamed from: create */
                public ErrorArgs m15010create(Parcel parcel) {
                    C3335k.m11451e(parcel, "parcel");
                    Serializable readSerializable = parcel.readSerializable();
                    C3335k.m11453c(readSerializable, "null cannot be cast to non-null type com.stripe.android.core.exception.StripeException");
                    return new ErrorArgs((StripeException) readSerializable, parcel.readInt());
                }

                public void write(ErrorArgs errorArgs, Parcel parcel, int i) {
                    C3335k.m11451e(errorArgs, "<this>");
                    C3335k.m11451e(parcel, "parcel");
                    parcel.writeSerializable(errorArgs.getException$payments_core_release());
                    parcel.writeInt(errorArgs.getRequestCode());
                }
            }

            /* compiled from: PaymentRelayStarter.kt */
            /* loaded from: classes.dex */
            public static final class Creator implements Parcelable.Creator<ErrorArgs> {
                /* JADX WARN: Can't rename method to resolve collision */
                @Override // android.os.Parcelable.Creator
                public final ErrorArgs createFromParcel(Parcel parcel) {
                    C3335k.m11451e(parcel, "parcel");
                    return ErrorArgs.Companion.m15010create(parcel);
                }

                /* JADX WARN: Can't rename method to resolve collision */
                @Override // android.os.Parcelable.Creator
                public final ErrorArgs[] newArray(int i) {
                    return new ErrorArgs[i];
                }
            }

            /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
            public ErrorArgs(StripeException stripeException, int i) {
                super(null);
                C3335k.m11451e(stripeException, "exception");
                this.exception = stripeException;
                this.requestCode = i;
            }

            public static /* synthetic */ ErrorArgs copy$default(ErrorArgs errorArgs, StripeException stripeException, int i, int i2, Object obj) {
                if ((i2 & 1) != 0) {
                    stripeException = errorArgs.exception;
                }
                if ((i2 & 2) != 0) {
                    i = errorArgs.getRequestCode();
                }
                return errorArgs.copy(stripeException, i);
            }

            public final StripeException component1$payments_core_release() {
                return this.exception;
            }

            public final int component2() {
                return getRequestCode();
            }

            public final ErrorArgs copy(StripeException stripeException, int i) {
                C3335k.m11451e(stripeException, "exception");
                return new ErrorArgs(stripeException, i);
            }

            @Override // android.os.Parcelable
            public int describeContents() {
                return 0;
            }

            public boolean equals(Object obj) {
                if (this == obj) {
                    return true;
                }
                if (obj instanceof ErrorArgs) {
                    ErrorArgs errorArgs = (ErrorArgs) obj;
                    return C3335k.m11455a(this.exception, errorArgs.exception) && getRequestCode() == errorArgs.getRequestCode();
                }
                return false;
            }

            public final StripeException getException$payments_core_release() {
                return this.exception;
            }

            @Override // com.stripe.android.PaymentRelayStarter.Args
            public int getRequestCode() {
                return this.requestCode;
            }

            public int hashCode() {
                return Integer.hashCode(getRequestCode()) + (this.exception.hashCode() * 31);
            }

            @Override // com.stripe.android.PaymentRelayStarter.Args
            public PaymentFlowResult.Unvalidated toResult() {
                return new PaymentFlowResult.Unvalidated(null, 0, this.exception, false, null, null, null, 123, null);
            }

            public String toString() {
                StringBuilder m14987g = C0048o.m14987g("ErrorArgs(exception=");
                m14987g.append(this.exception);
                m14987g.append(", requestCode=");
                m14987g.append(getRequestCode());
                m14987g.append(')');
                return m14987g.toString();
            }

            @Override // android.os.Parcelable
            public void writeToParcel(Parcel parcel, int i) {
                C3335k.m11451e(parcel, "out");
                Companion.write(this, parcel, i);
            }
        }

        /* compiled from: PaymentRelayStarter.kt */
        /* loaded from: classes.dex */
        public static final class PaymentIntentArgs extends Args {
            private final PaymentIntent paymentIntent;
            private final String stripeAccountId;
            public static final Parcelable.Creator<PaymentIntentArgs> CREATOR = new Creator();
            public static final int $stable = 8;

            /* compiled from: PaymentRelayStarter.kt */
            /* loaded from: classes.dex */
            public static final class Creator implements Parcelable.Creator<PaymentIntentArgs> {
                /* JADX WARN: Can't rename method to resolve collision */
                @Override // android.os.Parcelable.Creator
                public final PaymentIntentArgs createFromParcel(Parcel parcel) {
                    C3335k.m11451e(parcel, "parcel");
                    return new PaymentIntentArgs(PaymentIntent.CREATOR.createFromParcel(parcel), parcel.readString());
                }

                /* JADX WARN: Can't rename method to resolve collision */
                @Override // android.os.Parcelable.Creator
                public final PaymentIntentArgs[] newArray(int i) {
                    return new PaymentIntentArgs[i];
                }
            }

            public /* synthetic */ PaymentIntentArgs(PaymentIntent paymentIntent, String str, int i, C3330f c3330f) {
                this(paymentIntent, (i & 2) != 0 ? null : str);
            }

            public static /* synthetic */ PaymentIntentArgs copy$default(PaymentIntentArgs paymentIntentArgs, PaymentIntent paymentIntent, String str, int i, Object obj) {
                if ((i & 1) != 0) {
                    paymentIntent = paymentIntentArgs.paymentIntent;
                }
                if ((i & 2) != 0) {
                    str = paymentIntentArgs.stripeAccountId;
                }
                return paymentIntentArgs.copy(paymentIntent, str);
            }

            public final PaymentIntent component1$payments_core_release() {
                return this.paymentIntent;
            }

            public final String component2$payments_core_release() {
                return this.stripeAccountId;
            }

            public final PaymentIntentArgs copy(PaymentIntent paymentIntent, String str) {
                C3335k.m11451e(paymentIntent, "paymentIntent");
                return new PaymentIntentArgs(paymentIntent, str);
            }

            @Override // android.os.Parcelable
            public int describeContents() {
                return 0;
            }

            public boolean equals(Object obj) {
                if (this == obj) {
                    return true;
                }
                if (obj instanceof PaymentIntentArgs) {
                    PaymentIntentArgs paymentIntentArgs = (PaymentIntentArgs) obj;
                    return C3335k.m11455a(this.paymentIntent, paymentIntentArgs.paymentIntent) && C3335k.m11455a(this.stripeAccountId, paymentIntentArgs.stripeAccountId);
                }
                return false;
            }

            public final PaymentIntent getPaymentIntent$payments_core_release() {
                return this.paymentIntent;
            }

            @Override // com.stripe.android.PaymentRelayStarter.Args
            public int getRequestCode() {
                return StripePaymentController.PAYMENT_REQUEST_CODE;
            }

            public final String getStripeAccountId$payments_core_release() {
                return this.stripeAccountId;
            }

            public int hashCode() {
                int hashCode = this.paymentIntent.hashCode() * 31;
                String str = this.stripeAccountId;
                return hashCode + (str == null ? 0 : str.hashCode());
            }

            @Override // com.stripe.android.PaymentRelayStarter.Args
            public PaymentFlowResult.Unvalidated toResult() {
                return new PaymentFlowResult.Unvalidated(this.paymentIntent.getClientSecret(), 0, null, false, null, null, this.stripeAccountId, 62, null);
            }

            public String toString() {
                StringBuilder m14987g = C0048o.m14987g("PaymentIntentArgs(paymentIntent=");
                m14987g.append(this.paymentIntent);
                m14987g.append(", stripeAccountId=");
                return C0118m0.m14942c(m14987g, this.stripeAccountId, ')');
            }

            @Override // android.os.Parcelable
            public void writeToParcel(Parcel parcel, int i) {
                C3335k.m11451e(parcel, "out");
                this.paymentIntent.writeToParcel(parcel, i);
                parcel.writeString(this.stripeAccountId);
            }

            /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
            public PaymentIntentArgs(PaymentIntent paymentIntent, String str) {
                super(null);
                C3335k.m11451e(paymentIntent, "paymentIntent");
                this.paymentIntent = paymentIntent;
                this.stripeAccountId = str;
            }
        }

        /* compiled from: PaymentRelayStarter.kt */
        /* loaded from: classes.dex */
        public static final class SetupIntentArgs extends Args {
            private final SetupIntent setupIntent;
            private final String stripeAccountId;
            public static final Parcelable.Creator<SetupIntentArgs> CREATOR = new Creator();
            public static final int $stable = 8;

            /* compiled from: PaymentRelayStarter.kt */
            /* loaded from: classes.dex */
            public static final class Creator implements Parcelable.Creator<SetupIntentArgs> {
                /* JADX WARN: Can't rename method to resolve collision */
                @Override // android.os.Parcelable.Creator
                public final SetupIntentArgs createFromParcel(Parcel parcel) {
                    C3335k.m11451e(parcel, "parcel");
                    return new SetupIntentArgs(SetupIntent.CREATOR.createFromParcel(parcel), parcel.readString());
                }

                /* JADX WARN: Can't rename method to resolve collision */
                @Override // android.os.Parcelable.Creator
                public final SetupIntentArgs[] newArray(int i) {
                    return new SetupIntentArgs[i];
                }
            }

            public /* synthetic */ SetupIntentArgs(SetupIntent setupIntent, String str, int i, C3330f c3330f) {
                this(setupIntent, (i & 2) != 0 ? null : str);
            }

            public static /* synthetic */ SetupIntentArgs copy$default(SetupIntentArgs setupIntentArgs, SetupIntent setupIntent, String str, int i, Object obj) {
                if ((i & 1) != 0) {
                    setupIntent = setupIntentArgs.setupIntent;
                }
                if ((i & 2) != 0) {
                    str = setupIntentArgs.stripeAccountId;
                }
                return setupIntentArgs.copy(setupIntent, str);
            }

            public final SetupIntent component1$payments_core_release() {
                return this.setupIntent;
            }

            public final String component2$payments_core_release() {
                return this.stripeAccountId;
            }

            public final SetupIntentArgs copy(SetupIntent setupIntent, String str) {
                C3335k.m11451e(setupIntent, "setupIntent");
                return new SetupIntentArgs(setupIntent, str);
            }

            @Override // android.os.Parcelable
            public int describeContents() {
                return 0;
            }

            public boolean equals(Object obj) {
                if (this == obj) {
                    return true;
                }
                if (obj instanceof SetupIntentArgs) {
                    SetupIntentArgs setupIntentArgs = (SetupIntentArgs) obj;
                    return C3335k.m11455a(this.setupIntent, setupIntentArgs.setupIntent) && C3335k.m11455a(this.stripeAccountId, setupIntentArgs.stripeAccountId);
                }
                return false;
            }

            @Override // com.stripe.android.PaymentRelayStarter.Args
            public int getRequestCode() {
                return StripePaymentController.SETUP_REQUEST_CODE;
            }

            public final SetupIntent getSetupIntent$payments_core_release() {
                return this.setupIntent;
            }

            public final String getStripeAccountId$payments_core_release() {
                return this.stripeAccountId;
            }

            public int hashCode() {
                int hashCode = this.setupIntent.hashCode() * 31;
                String str = this.stripeAccountId;
                return hashCode + (str == null ? 0 : str.hashCode());
            }

            @Override // com.stripe.android.PaymentRelayStarter.Args
            public PaymentFlowResult.Unvalidated toResult() {
                return new PaymentFlowResult.Unvalidated(this.setupIntent.getClientSecret(), 0, null, false, null, null, this.stripeAccountId, 62, null);
            }

            public String toString() {
                StringBuilder m14987g = C0048o.m14987g("SetupIntentArgs(setupIntent=");
                m14987g.append(this.setupIntent);
                m14987g.append(", stripeAccountId=");
                return C0118m0.m14942c(m14987g, this.stripeAccountId, ')');
            }

            @Override // android.os.Parcelable
            public void writeToParcel(Parcel parcel, int i) {
                C3335k.m11451e(parcel, "out");
                this.setupIntent.writeToParcel(parcel, i);
                parcel.writeString(this.stripeAccountId);
            }

            /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
            public SetupIntentArgs(SetupIntent setupIntent, String str) {
                super(null);
                C3335k.m11451e(setupIntent, "setupIntent");
                this.setupIntent = setupIntent;
                this.stripeAccountId = str;
            }
        }

        /* compiled from: PaymentRelayStarter.kt */
        /* loaded from: classes.dex */
        public static final class SourceArgs extends Args {
            private final Source source;
            private final String stripeAccountId;
            public static final Parcelable.Creator<SourceArgs> CREATOR = new Creator();
            public static final int $stable = 8;

            /* compiled from: PaymentRelayStarter.kt */
            /* loaded from: classes.dex */
            public static final class Creator implements Parcelable.Creator<SourceArgs> {
                /* JADX WARN: Can't rename method to resolve collision */
                @Override // android.os.Parcelable.Creator
                public final SourceArgs createFromParcel(Parcel parcel) {
                    C3335k.m11451e(parcel, "parcel");
                    return new SourceArgs(Source.CREATOR.createFromParcel(parcel), parcel.readString());
                }

                /* JADX WARN: Can't rename method to resolve collision */
                @Override // android.os.Parcelable.Creator
                public final SourceArgs[] newArray(int i) {
                    return new SourceArgs[i];
                }
            }

            public /* synthetic */ SourceArgs(Source source, String str, int i, C3330f c3330f) {
                this(source, (i & 2) != 0 ? null : str);
            }

            public static /* synthetic */ SourceArgs copy$default(SourceArgs sourceArgs, Source source, String str, int i, Object obj) {
                if ((i & 1) != 0) {
                    source = sourceArgs.source;
                }
                if ((i & 2) != 0) {
                    str = sourceArgs.stripeAccountId;
                }
                return sourceArgs.copy(source, str);
            }

            public final Source component1$payments_core_release() {
                return this.source;
            }

            public final String component2$payments_core_release() {
                return this.stripeAccountId;
            }

            public final SourceArgs copy(Source source, String str) {
                C3335k.m11451e(source, Stripe3ds2AuthParams.FIELD_SOURCE);
                return new SourceArgs(source, str);
            }

            @Override // android.os.Parcelable
            public int describeContents() {
                return 0;
            }

            public boolean equals(Object obj) {
                if (this == obj) {
                    return true;
                }
                if (obj instanceof SourceArgs) {
                    SourceArgs sourceArgs = (SourceArgs) obj;
                    return C3335k.m11455a(this.source, sourceArgs.source) && C3335k.m11455a(this.stripeAccountId, sourceArgs.stripeAccountId);
                }
                return false;
            }

            @Override // com.stripe.android.PaymentRelayStarter.Args
            public int getRequestCode() {
                return StripePaymentController.SOURCE_REQUEST_CODE;
            }

            public final Source getSource$payments_core_release() {
                return this.source;
            }

            public final String getStripeAccountId$payments_core_release() {
                return this.stripeAccountId;
            }

            public int hashCode() {
                int hashCode = this.source.hashCode() * 31;
                String str = this.stripeAccountId;
                return hashCode + (str == null ? 0 : str.hashCode());
            }

            @Override // com.stripe.android.PaymentRelayStarter.Args
            public PaymentFlowResult.Unvalidated toResult() {
                return new PaymentFlowResult.Unvalidated(null, 0, null, false, null, this.source, this.stripeAccountId, 31, null);
            }

            public String toString() {
                StringBuilder m14987g = C0048o.m14987g("SourceArgs(source=");
                m14987g.append(this.source);
                m14987g.append(", stripeAccountId=");
                return C0118m0.m14942c(m14987g, this.stripeAccountId, ')');
            }

            @Override // android.os.Parcelable
            public void writeToParcel(Parcel parcel, int i) {
                C3335k.m11451e(parcel, "out");
                this.source.writeToParcel(parcel, i);
                parcel.writeString(this.stripeAccountId);
            }

            /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
            public SourceArgs(Source source, String str) {
                super(null);
                C3335k.m11451e(source, Stripe3ds2AuthParams.FIELD_SOURCE);
                this.source = source;
                this.stripeAccountId = str;
            }
        }

        private Args() {
        }

        public /* synthetic */ Args(C3330f c3330f) {
            this();
        }

        public abstract int getRequestCode();

        public abstract PaymentFlowResult.Unvalidated toResult();
    }

    /* compiled from: PaymentRelayStarter.kt */
    /* loaded from: classes.dex */
    public static final class Legacy implements PaymentRelayStarter {
        public static final int $stable = 0;
        private final AuthActivityStarterHost host;

        public Legacy(AuthActivityStarterHost authActivityStarterHost) {
            C3335k.m11451e(authActivityStarterHost, "host");
            this.host = authActivityStarterHost;
        }

        @Override // com.stripe.android.view.AuthActivityStarter
        public void start(Args args) {
            C3335k.m11451e(args, "args");
            this.host.startActivityForResult(PaymentRelayActivity.class, args.toResult().toBundle(), args.getRequestCode());
        }
    }

    /* compiled from: PaymentRelayStarter.kt */
    /* loaded from: classes.dex */
    public static final class Modern implements PaymentRelayStarter {
        public static final int $stable = 8;
        private final AbstractC0343d<Args> launcher;

        public Modern(AbstractC0343d<Args> abstractC0343d) {
            C3335k.m11451e(abstractC0343d, "launcher");
            this.launcher = abstractC0343d;
        }

        @Override // com.stripe.android.view.AuthActivityStarter
        public void start(Args args) {
            C3335k.m11451e(args, "args");
            this.launcher.mo11644a(args);
        }
    }
}
