package com.stripe.android.googlepaylauncher;

import android.content.Intent;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.common.api.Status;
import com.stripe.android.model.PaymentMethod;
import com.stripe.android.model.ShippingInformation;
import com.stripe.android.view.ActivityStarter;
import java.io.Serializable;
import p001a.C0048o;
import p020b0.C1226i0;
import p072df.C3330f;
import p072df.C3335k;
import p353te.C9453f;
import p353te.C9454g;
/* compiled from: GooglePayLauncherResult.kt */
/* loaded from: classes.dex */
public abstract class GooglePayLauncherResult implements ActivityStarter.Result {
    public static final Companion Companion = new Companion(null);

    /* compiled from: GooglePayLauncherResult.kt */
    /* loaded from: classes.dex */
    public static final class Canceled extends GooglePayLauncherResult {
        public static final Canceled INSTANCE = new Canceled();
        public static final Parcelable.Creator<Canceled> CREATOR = new Creator();

        /* compiled from: GooglePayLauncherResult.kt */
        /* loaded from: classes.dex */
        public static final class Creator implements Parcelable.Creator<Canceled> {
            /* JADX WARN: Can't rename method to resolve collision */
            @Override // android.os.Parcelable.Creator
            public final Canceled createFromParcel(Parcel parcel) {
                C3335k.m11451e(parcel, "parcel");
                parcel.readInt();
                return Canceled.INSTANCE;
            }

            /* JADX WARN: Can't rename method to resolve collision */
            @Override // android.os.Parcelable.Creator
            public final Canceled[] newArray(int i) {
                return new Canceled[i];
            }
        }

        private Canceled() {
            super(null);
        }

        @Override // android.os.Parcelable
        public int describeContents() {
            return 0;
        }

        @Override // android.os.Parcelable
        public void writeToParcel(Parcel parcel, int i) {
            C3335k.m11451e(parcel, "out");
            parcel.writeInt(1);
        }
    }

    /* compiled from: GooglePayLauncherResult.kt */
    /* loaded from: classes.dex */
    public static final class Companion {
        private Companion() {
        }

        public /* synthetic */ Companion(C3330f c3330f) {
            this();
        }

        public final GooglePayLauncherResult fromIntent(Intent intent) {
            GooglePayLauncherResult googlePayLauncherResult;
            if (intent != null) {
                googlePayLauncherResult = (GooglePayLauncherResult) intent.getParcelableExtra("extra_activity_result");
            } else {
                googlePayLauncherResult = null;
            }
            if (googlePayLauncherResult == null) {
                return new Error(new IllegalStateException("Error while processing result from Google Pay."), null, null, null, 14, null);
            }
            return googlePayLauncherResult;
        }
    }

    /* compiled from: GooglePayLauncherResult.kt */
    /* loaded from: classes.dex */
    public static final class Error extends GooglePayLauncherResult {
        private final Throwable exception;
        private final Status googlePayStatus;
        private final PaymentMethod paymentMethod;
        private final ShippingInformation shippingInformation;
        public static final Companion Companion = new Companion(null);
        public static final Parcelable.Creator<Error> CREATOR = new Creator();

        /* compiled from: GooglePayLauncherResult.kt */
        /* loaded from: classes.dex */
        public static final class Companion {
            private Companion() {
            }

            public /* synthetic */ Companion(C3330f c3330f) {
                this();
            }

            /* renamed from: create */
            public Error m15143create(Parcel parcel) {
                C3335k.m11451e(parcel, "parcel");
                Serializable readSerializable = parcel.readSerializable();
                C3335k.m11453c(readSerializable, "null cannot be cast to non-null type kotlin.Throwable");
                return new Error((Throwable) readSerializable, (Status) parcel.readParcelable(Status.class.getClassLoader()), null, null, 12, null);
            }

            /* renamed from: newArray */
            public Error[] m15144newArray(int i) {
                throw new C9453f("Generated by Android Extensions automatically");
            }

            public void write(Error error, Parcel parcel, int i) {
                C3335k.m11451e(error, "<this>");
                C3335k.m11451e(parcel, "parcel");
                parcel.writeSerializable(error.getException());
                parcel.writeParcelable(error.getGooglePayStatus(), i);
            }
        }

        /* compiled from: GooglePayLauncherResult.kt */
        /* loaded from: classes.dex */
        public static final class Creator implements Parcelable.Creator<Error> {
            /* JADX WARN: Can't rename method to resolve collision */
            @Override // android.os.Parcelable.Creator
            public final Error createFromParcel(Parcel parcel) {
                C3335k.m11451e(parcel, "parcel");
                return Error.Companion.m15143create(parcel);
            }

            /* JADX WARN: Can't rename method to resolve collision */
            @Override // android.os.Parcelable.Creator
            public final Error[] newArray(int i) {
                return new Error[i];
            }
        }

        public /* synthetic */ Error(Throwable th2, Status status, PaymentMethod paymentMethod, ShippingInformation shippingInformation, int i, C3330f c3330f) {
            this(th2, (i & 2) != 0 ? null : status, (i & 4) != 0 ? null : paymentMethod, (i & 8) != 0 ? null : shippingInformation);
        }

        public static /* synthetic */ Error copy$default(Error error, Throwable th2, Status status, PaymentMethod paymentMethod, ShippingInformation shippingInformation, int i, Object obj) {
            if ((i & 1) != 0) {
                th2 = error.exception;
            }
            if ((i & 2) != 0) {
                status = error.googlePayStatus;
            }
            if ((i & 4) != 0) {
                paymentMethod = error.paymentMethod;
            }
            if ((i & 8) != 0) {
                shippingInformation = error.shippingInformation;
            }
            return error.copy(th2, status, paymentMethod, shippingInformation);
        }

        public final Throwable component1() {
            return this.exception;
        }

        public final Status component2() {
            return this.googlePayStatus;
        }

        public final PaymentMethod component3() {
            return this.paymentMethod;
        }

        public final ShippingInformation component4() {
            return this.shippingInformation;
        }

        public final Error copy(Throwable th2, Status status, PaymentMethod paymentMethod, ShippingInformation shippingInformation) {
            C3335k.m11451e(th2, "exception");
            return new Error(th2, status, paymentMethod, shippingInformation);
        }

        @Override // android.os.Parcelable
        public int describeContents() {
            return 0;
        }

        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (obj instanceof Error) {
                Error error = (Error) obj;
                return C3335k.m11455a(this.exception, error.exception) && C3335k.m11455a(this.googlePayStatus, error.googlePayStatus) && C3335k.m11455a(this.paymentMethod, error.paymentMethod) && C3335k.m11455a(this.shippingInformation, error.shippingInformation);
            }
            return false;
        }

        public final Throwable getException() {
            return this.exception;
        }

        public final Status getGooglePayStatus() {
            return this.googlePayStatus;
        }

        public final PaymentMethod getPaymentMethod() {
            return this.paymentMethod;
        }

        public final ShippingInformation getShippingInformation() {
            return this.shippingInformation;
        }

        public int hashCode() {
            int hashCode = this.exception.hashCode() * 31;
            Status status = this.googlePayStatus;
            int hashCode2 = (hashCode + (status == null ? 0 : status.hashCode())) * 31;
            PaymentMethod paymentMethod = this.paymentMethod;
            int hashCode3 = (hashCode2 + (paymentMethod == null ? 0 : paymentMethod.hashCode())) * 31;
            ShippingInformation shippingInformation = this.shippingInformation;
            return hashCode3 + (shippingInformation != null ? shippingInformation.hashCode() : 0);
        }

        public String toString() {
            StringBuilder m14987g = C0048o.m14987g("Error(exception=");
            m14987g.append(this.exception);
            m14987g.append(", googlePayStatus=");
            m14987g.append(this.googlePayStatus);
            m14987g.append(", paymentMethod=");
            m14987g.append(this.paymentMethod);
            m14987g.append(", shippingInformation=");
            m14987g.append(this.shippingInformation);
            m14987g.append(')');
            return m14987g.toString();
        }

        @Override // android.os.Parcelable
        public void writeToParcel(Parcel parcel, int i) {
            C3335k.m11451e(parcel, "out");
            Companion.write(this, parcel, i);
        }

        /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
        public Error(Throwable th2, Status status, PaymentMethod paymentMethod, ShippingInformation shippingInformation) {
            super(null);
            C3335k.m11451e(th2, "exception");
            this.exception = th2;
            this.googlePayStatus = status;
            this.paymentMethod = paymentMethod;
            this.shippingInformation = shippingInformation;
        }
    }

    /* compiled from: GooglePayLauncherResult.kt */
    /* loaded from: classes.dex */
    public static final class PaymentData extends GooglePayLauncherResult {
        public static final Parcelable.Creator<PaymentData> CREATOR = new Creator();
        private final PaymentMethod paymentMethod;
        private final ShippingInformation shippingInformation;

        /* compiled from: GooglePayLauncherResult.kt */
        /* loaded from: classes.dex */
        public static final class Creator implements Parcelable.Creator<PaymentData> {
            /* JADX WARN: Can't rename method to resolve collision */
            @Override // android.os.Parcelable.Creator
            public final PaymentData createFromParcel(Parcel parcel) {
                C3335k.m11451e(parcel, "parcel");
                return new PaymentData(PaymentMethod.CREATOR.createFromParcel(parcel), parcel.readInt() == 0 ? null : ShippingInformation.CREATOR.createFromParcel(parcel));
            }

            /* JADX WARN: Can't rename method to resolve collision */
            @Override // android.os.Parcelable.Creator
            public final PaymentData[] newArray(int i) {
                return new PaymentData[i];
            }
        }

        /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
        public PaymentData(PaymentMethod paymentMethod, ShippingInformation shippingInformation) {
            super(null);
            C3335k.m11451e(paymentMethod, "paymentMethod");
            this.paymentMethod = paymentMethod;
            this.shippingInformation = shippingInformation;
        }

        public static /* synthetic */ PaymentData copy$default(PaymentData paymentData, PaymentMethod paymentMethod, ShippingInformation shippingInformation, int i, Object obj) {
            if ((i & 1) != 0) {
                paymentMethod = paymentData.paymentMethod;
            }
            if ((i & 2) != 0) {
                shippingInformation = paymentData.shippingInformation;
            }
            return paymentData.copy(paymentMethod, shippingInformation);
        }

        public final PaymentMethod component1() {
            return this.paymentMethod;
        }

        public final ShippingInformation component2() {
            return this.shippingInformation;
        }

        public final PaymentData copy(PaymentMethod paymentMethod, ShippingInformation shippingInformation) {
            C3335k.m11451e(paymentMethod, "paymentMethod");
            return new PaymentData(paymentMethod, shippingInformation);
        }

        @Override // android.os.Parcelable
        public int describeContents() {
            return 0;
        }

        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (obj instanceof PaymentData) {
                PaymentData paymentData = (PaymentData) obj;
                return C3335k.m11455a(this.paymentMethod, paymentData.paymentMethod) && C3335k.m11455a(this.shippingInformation, paymentData.shippingInformation);
            }
            return false;
        }

        public final PaymentMethod getPaymentMethod() {
            return this.paymentMethod;
        }

        public final ShippingInformation getShippingInformation() {
            return this.shippingInformation;
        }

        public int hashCode() {
            int hashCode = this.paymentMethod.hashCode() * 31;
            ShippingInformation shippingInformation = this.shippingInformation;
            return hashCode + (shippingInformation == null ? 0 : shippingInformation.hashCode());
        }

        public String toString() {
            StringBuilder m14987g = C0048o.m14987g("PaymentData(paymentMethod=");
            m14987g.append(this.paymentMethod);
            m14987g.append(", shippingInformation=");
            m14987g.append(this.shippingInformation);
            m14987g.append(')');
            return m14987g.toString();
        }

        @Override // android.os.Parcelable
        public void writeToParcel(Parcel parcel, int i) {
            C3335k.m11451e(parcel, "out");
            this.paymentMethod.writeToParcel(parcel, i);
            ShippingInformation shippingInformation = this.shippingInformation;
            if (shippingInformation == null) {
                parcel.writeInt(0);
                return;
            }
            parcel.writeInt(1);
            shippingInformation.writeToParcel(parcel, i);
        }
    }

    /* compiled from: GooglePayLauncherResult.kt */
    /* loaded from: classes.dex */
    public static final class Unavailable extends GooglePayLauncherResult {
        public static final Unavailable INSTANCE = new Unavailable();
        public static final Parcelable.Creator<Unavailable> CREATOR = new Creator();

        /* compiled from: GooglePayLauncherResult.kt */
        /* loaded from: classes.dex */
        public static final class Creator implements Parcelable.Creator<Unavailable> {
            /* JADX WARN: Can't rename method to resolve collision */
            @Override // android.os.Parcelable.Creator
            public final Unavailable createFromParcel(Parcel parcel) {
                C3335k.m11451e(parcel, "parcel");
                parcel.readInt();
                return Unavailable.INSTANCE;
            }

            /* JADX WARN: Can't rename method to resolve collision */
            @Override // android.os.Parcelable.Creator
            public final Unavailable[] newArray(int i) {
                return new Unavailable[i];
            }
        }

        private Unavailable() {
            super(null);
        }

        @Override // android.os.Parcelable
        public int describeContents() {
            return 0;
        }

        @Override // android.os.Parcelable
        public void writeToParcel(Parcel parcel, int i) {
            C3335k.m11451e(parcel, "out");
            parcel.writeInt(1);
        }
    }

    private GooglePayLauncherResult() {
    }

    public /* synthetic */ GooglePayLauncherResult(C3330f c3330f) {
        this();
    }

    public static final GooglePayLauncherResult fromIntent(Intent intent) {
        return Companion.fromIntent(intent);
    }

    @Override // com.stripe.android.view.ActivityStarter.Result
    public Bundle toBundle() {
        return C1226i0.m12821D(new C9454g("extra_activity_result", this));
    }
}
